
#include <stdint.h>
#include "stm32f446xx.h"
#include <stdio.h>
#include <stddef.h>



void delay()
{
	for(uint32_t i=0;i<500000;i++);
}

int main(void)
{
	RCC->AHB1ENR |=(1<<0);
	GPIOA->MODER |= (1<<10);
	GPIOA->OTYPER &=~(1<<5);
	GPIOA->OSPEEDR |=(1<<10);

	GPIOA->PUPDR &=~(3<<10);

    /* Loop forever */

	printf("Hello world\n");
	for(;;)
		{
			GPIOA->ODR |= (1<<5);
			delay();
			GPIOA->ODR &= ~(1<<5);
			delay();

		}




}


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include <stdint.h>
//
//uint32_t *AHB1ENR = (uint32_t*) 0x40023830;
//
//uint32_t *DMA2_S0CR = (uint32_t*)0x40026410;		//control register
//uint32_t *DMA2_S0NDTR = (uint32_t*)0x40026414;
//uint32_t *DMA2_S0PAR = (uint32_t*)0x40026418;
//uint32_t *DMA2_S0M0AR = (uint32_t*)0x4002641C;
//
//void DMA2_init();
//void DMA2_Start();
//
//char source[8]="HELOYES";
//char dest[8];
//char dest1[4];
//
//int main(void)
//{
//    DMA2_init();
//    DMA2_Start();
//    while(1)
//    {
//    }
//}
//
//void DMA2_init()
//{
//	*AHB1ENR |= (1<<22); 		//Enable DMA2 RCC
//	*DMA2_S0CR |= (2<<6);		//Data transfer direction M2M
//	*DMA2_S0CR &= ~(1<<25);		//Channel selection - channel number 0
//	*DMA2_S0CR |= (0<<16);		//Priority level L/M/H
//	*DMA2_S0CR |= (1<<10);		//Memory increment mode
//	*DMA2_S0CR &= ~(1<<13);		//Memory data size - 8 bit
//	*DMA2_S0CR |= (1<<9);		//Peripheral increment mode
//	*DMA2_S0CR &= ~(1<<11);		//Peripheral data size - 8 bit
//}
//
//void DMA2_Start()
//{
//	*DMA2_S0NDTR = 8;			//No of data bytes
//	*DMA2_S0M0AR = (uint32_t) &dest;	//Destination address
//	*DMA2_S0PAR = (uint32_t) &source;	//Source address
//	*DMA2_S0CR |= (1<<0);		//Start transfer
//}
